# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='活动名称')),
                ('date', models.DateField(blank=True, verbose_name='日期')),
                ('time', models.TimeField(blank=True, verbose_name='开始时间')),
                ('place', models.CharField(blank=True, max_length=15, verbose_name='地点')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('participation', models.SmallIntegerField(default=0, verbose_name='参与得分')),
                ('participator', models.TextField(blank=True, verbose_name='参与者学号')),
                ('images', models.TextField(blank=True, verbose_name='相关图片urls')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=12, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('pinyin', models.CharField(max_length=25, verbose_name='拼音')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, verbose_name='性别')),
                ('native_province', models.CharField(blank=True, max_length=10, verbose_name='籍贯')),
                ('dormitory', models.CharField(blank=True, max_length=7, verbose_name='寝室')),
                ('birthday', models.DateField(blank=True, verbose_name='生日')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='职务')),
                ('participation', models.PositiveSmallIntegerField(default=0, verbose_name='活动参与分')),
            ],
        ),
    ]
